from __future__ import absolute_import, print_function

import json
import logging
import os
import time
import urllib2

from threading import Event
from uuid import uuid4

try:
    from mesos.interface import Scheduler
    from mesos.interface import mesos_pb2
except ImportError:
    from mesos import Scheduler
    import mesos_pb2


class FileBlacklist(object):
    """ File-backed blacklist for slave hostnames.
    Hosts are expected to be named in the file, one per line.
    Whitespace and lines beginning with '#' are ignored.
    """
    def __init__(self, path):
        self._path = path
        self._mtime = 0
        self._blacklist = set()

    def refresh(self):
        """Refresh the blacklist if the file changed."""
        if os.path.getmtime(self._path) > self._mtime:
            self._refresh()

    def _refresh(self):
        """Unconditionally refresh the blacklist from the file."""
        logging.info('Refreshing blacklist')
        self._mtime = int(time.time())
        with open(self._path) as file:
            self._blacklist = set([s.strip() for s in file.readlines() if not s.startswith('#')])

    def contains(self, hostname):
        """Returns whether the provided hostname is present in the blacklist as of last reading."""
        return hostname in self._blacklist


class ChangesScheduler(Scheduler):
    def __init__(self, api_url, config_dir, state_file):
        self.framework_id = None
        self.api_url = api_url
        self.taskJobStepMapping = {}
        self.tasksLaunched = 0
        self.tasksFinished = 0
        self.shuttingDown = Event()
        self._blacklist = FileBlacklist(os.path.join(config_dir, 'blacklist'))
        # Refresh now so that if it fails, it fails at startup.
        self._blacklist.refresh()
        self.state_file = state_file

        # Restore state from a previous run
        if not self.state_file:
            logging.warning("State file location not set. Not restoring old state.")
        elif not os.path.exists(self.state_file):
            logging.warning("State file not found. Not restoring old state.")
        else:
            try:
                self.restore_state()
            except Exception:
                logging.exception("Failed to restore state. Continuing as a new scheduler.")
            else:
                # Delete the old file to prevent it from being used again on a restart
                # as it will likely be stale.
                os.remove(self.state_file)

    def registered(self, driver, frameworkId, masterInfo):
        """
          Invoked when the scheduler successfully registers with a Mesos master.
          It is called with the frameworkId, a unique ID generated by the
          master, and the masterInfo which is information about the master
          itself.
        """
        logging.info("Registered with framework ID %s", frameworkId.value)
        self.framework_id = frameworkId.value

    def reregistered(self, driver, masterInfo):
        """
          Invoked when the scheduler re-registers with a newly elected Mesos
          master.  This is only called when the scheduler has previously been
          registered.  masterInfo contains information about the newly elected
          master.
        """
        logging.info("Re-Registered with new master")

    def disconnected(self, driver):
        """
          Invoked when the scheduler becomes disconnected from the master, e.g.
          the master fails and another is taking over.
        """
        logging.info("Disconnected from master")

    @staticmethod
    def _decode_typed_field(pb):
        field_type = pb.type
        if field_type == 0:  # Scalar
            return pb.scalar.value
        elif field_type == 1:  # Ranges
            return [{"begin": ra.begin, "end": ra.end} for ra in pb.ranges.range]
        elif field_type == 2:  # Set
            return pb.set.item
        elif field_type == 3:  # Text
            return pb.text.value
        else:
            raise Exception("Unknown field type: %s", field_type)

    @staticmethod
    def _decode_attribute(attr_pb):
        return {attr_pb.name: ChangesScheduler._decode_typed_field(attr_pb)}

    @staticmethod
    def _decode_resource(resource_pb):
        return (resource_pb.name, ChangesScheduler._decode_typed_field(resource_pb))

    @property
    def activeTasks(self):
        return self.tasksFinished - self.tasksLaunched

    def resourceOffers(self, driver, offers):
        """
          Invoked when resources have been offered to this framework. A single
          offer will only contain resources from a single slave.  Resources
          associated with an offer will not be re-offered to _this_ framework
          until either (a) this framework has rejected those resources (see
          SchedulerDriver.launchTasks) or (b) those resources have been
          rescinded (see Scheduler.offerRescinded).  Note that resources may be
          concurrently offered to more than one framework at a time (depending
          on the allocator being used).  In that case, the first framework to
          launch tasks using those resources will be able to use them while the
          other frameworks will have those resources rescinded (or if a
          framework has already launched tasks with those resources then those
          tasks will fail with a TASK_LOST status and a message saying as much).
        """
        logging.info("Got %d resource offers", len(offers))

        self._blacklist.refresh()

        for offer in offers:
            if self.shuttingDown.is_set():
                logging.info("Shutting down, declining offer: %s", offer.id)
                driver.declineOffer(offer.id)
                continue

            if self._blacklist.contains(offer.hostname):
                logging.info("Declining offer from blacklisted hostname: %s", offer.hostname)
                driver.declineOffer(offer.id)
                continue

            # protobuf -> dict
            info = {
                "attributes": [ChangesScheduler._decode_attribute(a) for a in offer.attributes],
                "executor_ids": [ei.value for ei in offer.executor_ids],
                "framework_id": offer.framework_id.value,
                "hostname": offer.hostname,
                "id": offer.id.value,
                "resources": {name: value
                              for (name, value)
                              in [ChangesScheduler._decode_resource(r) for r in offer.resources]},
                "slave_id": offer.slave_id.value,
            }
            logging.debug("Offer: %s", json.dumps(info, sort_keys=True, indent=2, separators=(',', ': ')))

            # hit service with our offer
            try:
                req = urllib2.Request(
                    self.api_url + "/jobsteps/allocate/", json.dumps(info),
                    {'Content-Type': 'application/json'})
                tasks_to_run = json.loads(urllib2.urlopen(req).read())
            except Exception:
                driver.declineOffer(offer.id)
                logging.exception("Error POSTing offer to service at %s", req.get_full_url())
                continue

            if len(tasks_to_run) == 0:
                logging.info("No tasks to run, declining offer: %s", offer.id)
                driver.declineOffer(offer.id)
                continue

            tasks = []
            for task_to_run in tasks_to_run:
                tid = uuid4().hex
                self.tasksLaunched += 1

                logging.info("Accepting offer on %s to start task %s", offer.hostname, tid)

                task = mesos_pb2.TaskInfo()
                task.name = "{} {}".format(
                    task_to_run['project']['slug'],
                    task_to_run['id'],
                )
                task.task_id.value = str(tid)
                task.slave_id.value = offer.slave_id.value

                cmd = task_to_run["cmd"]

                task.command.value = cmd
                logging.debug("Scheduling cmd: %s", cmd)

                # task.executor.MergeFrom(self.executor)
                # task.executor.data = task_to_run["cmd"].encode("utf-8")

                cpus = task.resources.add()
                cpus.name = "cpus"
                cpus.type = mesos_pb2.Value.SCALAR
                cpus.scalar.value = task_to_run["resources"]["cpus"]

                mem = task.resources.add()
                mem.name = "mem"
                mem.type = mesos_pb2.Value.SCALAR
                mem.scalar.value = task_to_run["resources"]["mem"]

                tasks.append(task)

                self.taskJobStepMapping[task.task_id.value] = task_to_run['id']
            driver.launchTasks(offer.id, tasks)

    def offerRescinded(self, driver, offerId):
        """
          Invoked when an offer is no longer valid (e.g., the slave was lost or
          another framework used resources in the offer.) If for whatever reason
          an offer is never rescinded (e.g., dropped message, failing over
          framework, etc.), a framwork that attempts to launch tasks using an
          invalid offer will receive TASK_LOST status updats for those tasks
          (see Scheduler.resourceOffers).
        """
        logging.info("Offer rescinded: %s", offerId.value)

    def statusUpdate(self, driver, status):
        """
          Invoked when the status of a task has changed (e.g., a slave is lost
          and so the task is lost, a task finishes and an executor sends a
          status update saying so, etc.) Note that returning from this callback
          acknowledges receipt of this status update.  If for whatever reason
          the scheduler aborts during this callback (or the process exits)
          another status update will be delivered.  Note, however, that this is
          currently not true if the slave sending the status update is lost or
          fails during that time.
        """

        states = {
            0: "starting",
            1: "running",
            2: "finished",  # terminal
            3: "failed",  # terminal
            4: "killed",  # terminal
            5: "lost",  # terminal
            6: "staging",
        }

        state = states[status.state]
        logging.info("Task %s is in state %d", status.task_id.value, status.state)

        jobstep_id = self.taskJobStepMapping.get(status.task_id.value)

        if status.state == mesos_pb2.TASK_FINISHED:
            self.tasksFinished += 1

            self.taskJobStepMapping.pop(status.task_id.value, None)

        def api_request(url, body):
            full_url = self.api_url + url
            try:
                req = urllib2.Request(
                    full_url, json.dumps(body),
                    {'Content-Type': 'application/json'})
                urllib2.urlopen(req).read()
            except Exception:
                logging.exception("Error POSTing status update to service at %s",
                                  full_url)

        if not jobstep_id:
            # TODO(dcramer): how does this happen?
            logging.error("Task %s is missing JobStep ID", status.task_id.value)
            return

        # TODO(dcramer): when can we actually properly do deallocation?
        # Relying on the lxc-wrapper to mark things as in_progress at least
        # allows us to have a best-effort
        if state == 'finished':
            api_request("/jobsteps/%s/" % jobstep_id, {"status": "finished"})
        elif state in ('killed', 'lost', 'failed'):
            # Jobsteps are only intended to be executed once and should only exit non-zero or be
            # lost/killed by infrastructural issues, so we don't attempt to reschedule, and we mark
            # this down as an infrastructural failure. Note that this state may not mean that the
            # Jobstep will necessarily stop executing, but it means that the results will be
            # considered immediately invalid.
            logging.warn('Task %s %s: %s', jobstep_id, state, status.message)

            api_request(
                url='/jobsteps/%s/logappend/' % jobstep_id,
                body={
                    'text': '==> Scheduler marked task as %s (will NOT be retried):\n\n%s' % (
                        state, status.message),
                    'source': 'console',
                }
            )

            api_request("/jobsteps/%s/" % jobstep_id, {"status": "finished", "result": "infra_failed"})

    def frameworkMessage(self, driver, executorId, slaveId, message):
        """
          Invoked when an executor sends a message. These messages are best
          effort; do not expect a framework message to be retransmitted in any
          reliable fashion.
        """
        logging.info("Received message: %s", repr(str(message)))

    def slaveLost(self, driver, slaveId):
        """
          Invoked when a slave has been determined unreachable (e.g., machine
          failure, network partition.) Most frameworks will need to reschedule
          any tasks launched on this slave on a new slave.
        """
        logging.warn("Slave lost: %s", slaveId.value)

    def executorLost(self, driver, executorId, slaveId, status):
        """
          Invoked when an executor has exited/terminated. Note that any tasks
          running will have TASK_LOST status updates automatically generated.
        """
        logging.warn("Executor %s lost on slave %s", executorId.value, slaveId.value)

    def error(self, driver, message):
        """
          Invoked when there is an unrecoverable error in the scheduler or
          scheduler driver.  The driver will be aborted BEFORE invoking this
          callback.
        """
        logging.error("Error from Mesos: %s", message)

    def save_state(self):
        """
          Save current state to a file so that a restart of the scheduler can
          restore the state.
        """
        state = {}
        state['framework_id'] = self.framework_id
        state['taskJobStepMapping'] = self.taskJobStepMapping
        state['tasksLaunched'] = self.tasksLaunched
        state['tasksFinished'] = self.tasksFinished
        logging.info('Attempting to save state for framework %s with %d running tasks to %s',
                     self.framework_id, len(self.taskJobStepMapping), self.state_file)
        with open(self.state_file, 'w') as f:
            f.write(json.dumps(state))

    def restore_state(self):
        """
          Restores state from the previous run of the scheduler.
        """
        with open(self.state_file) as f:
            json_state = f.read()
        state = json.loads(json_state)

        self.framework_id = state['framework_id']
        self.taskJobStepMapping = state['taskJobStepMapping']
        self.tasksLaunched = state['tasksLaunched']
        self.tasksFinished = state['tasksFinished']

        logging.info('Restored state for framework %s with %d running tasks from %s',
                     self.framework_id, len(self.taskJobStepMapping), self.state_file)
